server:
  port: 8081
spring:
  datasource:
    url: jdbc:mariadb://localhost:3307/minicampus
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: 1704
  
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true
    
  mail:
    host: smtp.gmail.com
    port: 587
    username: wodud170@gmail.com
    password: kedl xiws pdrv ahtm
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          ssl:
            trust: smtp.gmail.com
            protocol: TLSv1.2
            
logging:
  level:
    root: info
    
mybatis:
  mapper-locations: mybatis/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

